//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetsmartzOnlineStore.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetsmartzStore_DBEntities : DbContext
    {
        public NetsmartzStore_DBEntities()
            : base("name=NetsmartzStore_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatagoryTbl> CatagoryTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
    }
}
