//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetsmartzOnlineStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        public int ProductID_PK { get; set; }
        public int CategoryID_FK { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual CatagoryTbl CatagoryTbl { get; set; }
    }
}
